### ISSUE TITLE
vitamio 5.0 播放视频黑屏

### ISSUE THREAD

**Issue by xmy1231** [ahpiau18/StreamPlayerVitamio5#2]
用官方的demo测试mediaplayer_video页面播放网络视频一直无法播放，测试videoview页面播放网络视频正常，但是视频非常的卡。用你的工程也是一样，请问怎么解决这个问题。

**Comment by salmanashraf** [comment]
I tested this url
http://astro3.rastream.com/raaga?type=.flv
and it is playing normaly.

**Comment by xmy1231** [comment]
@salmanashraf  bug还是一样的，播放网络视频还是黑屏。

**Comment by salmanashraf** [comment]
if you open this link on browser, you will understand it clearly, this is a fm link

**Comment by ahpiau18** [comment]
this is a radio link, and i should use Media Player to open it. i tried and it works.
